import { Election, Contest } from '@/lib/types/election.types'
import { ELECTION_SCHEDULE } from '@/lib/data/election-schedule'

/**
 * Generates county-specific mock elections based on the address string.
 * Address format: "Travis County, Texas" or just "Texas"
 */
export function getMockElectionsForAddress(address: string): (Election & { contests: Contest[] })[] {
  const parts = address.split(', ')
  const countyDisplay = parts.length > 1 ? parts[0] : null  // e.g. "Travis County"
  const stateName = parts[parts.length - 1]                  // e.g. "Texas"

  const stateEntry = Object.entries(ELECTION_SCHEDULE).find(
    ([, info]) => info.stateName === stateName
  )
  const stateFips = stateEntry?.[0]
  const stateInfo = stateEntry?.[1]
  const electionDate = stateInfo?.nextElection ?? '2026-11-03'
  const electionType = stateInfo?.electionType ?? 'Primary'
  const countyName = countyDisplay ?? stateName
  const electionId = `mock-${stateFips ?? 'xx'}-primary-2026`

  return [
    {
      id: electionId,
      external_id: electionId,
      name: `${stateName} 2026 ${electionType}`,
      election_date: electionDate,
      state: stateFips ?? null,
      zipcodes: null,
      contests: [
        // === FEDERAL ===
        {
          id: `${electionId}-us-senate`,
          election_id: electionId,
          office: 'U.S. Senator',
          contest_type: 'candidate',
          district: stateName,
          candidates: [
            { name: 'Patricia Okonkwo', party: 'Democratic' },
            { name: 'William Hargrove', party: 'Republican' },
            { name: 'Sandra Vidal', party: 'Libertarian' },
          ],
          referendum_question: null,
          referendum_yes_meaning: null,
          referendum_no_meaning: null,
        },
        {
          id: `${electionId}-us-rep`,
          election_id: electionId,
          office: 'U.S. Representative',
          contest_type: 'candidate',
          district: `${countyName} Congressional District`,
          candidates: [
            { name: 'Angela Reyes', party: 'Democratic' },
            { name: 'Thomas Bancroft', party: 'Republican' },
          ],
          referendum_question: null,
          referendum_yes_meaning: null,
          referendum_no_meaning: null,
        },
        // === STATEWIDE EXECUTIVE ===
        {
          id: `${electionId}-governor`,
          election_id: electionId,
          office: 'Governor',
          contest_type: 'candidate',
          district: stateName,
          candidates: [
            { name: 'Marcus Chen', party: 'Democratic' },
            { name: 'Laura Whitfield', party: 'Republican' },
          ],
          referendum_question: null,
          referendum_yes_meaning: null,
          referendum_no_meaning: null,
        },
        {
          id: `${electionId}-lt-governor`,
          election_id: electionId,
          office: 'Lieutenant Governor',
          contest_type: 'candidate',
          district: stateName,
          candidates: [
            { name: 'Rosa Martinez', party: 'Democratic' },
            { name: 'Dale Pemberton', party: 'Republican' },
          ],
          referendum_question: null,
          referendum_yes_meaning: null,
          referendum_no_meaning: null,
        },
        {
          id: `${electionId}-attorney-general`,
          election_id: electionId,
          office: 'Attorney General',
          contest_type: 'candidate',
          district: stateName,
          candidates: [
            { name: 'James Okafor', party: 'Democratic' },
            { name: 'Helen Driscoll', party: 'Republican' },
          ],
          referendum_question: null,
          referendum_yes_meaning: null,
          referendum_no_meaning: null,
        },
        {
          id: `${electionId}-comptroller`,
          election_id: electionId,
          office: 'Comptroller of Public Accounts',
          contest_type: 'candidate',
          district: stateName,
          candidates: [
            { name: 'Yolanda Nguyen', party: 'Democratic' },
            { name: 'Frank Stanton', party: 'Republican' },
          ],
          referendum_question: null,
          referendum_yes_meaning: null,
          referendum_no_meaning: null,
        },
        {
          id: `${electionId}-land-commissioner`,
          election_id: electionId,
          office: 'Commissioner of the General Land Office',
          contest_type: 'candidate',
          district: stateName,
          candidates: [
            { name: 'Carlos Ibarra', party: 'Democratic' },
            { name: 'Meredith Hollis', party: 'Republican' },
          ],
          referendum_question: null,
          referendum_yes_meaning: null,
          referendum_no_meaning: null,
        },
        {
          id: `${electionId}-agriculture-commissioner`,
          election_id: electionId,
          office: 'Commissioner of Agriculture',
          contest_type: 'candidate',
          district: stateName,
          candidates: [
            { name: 'DeShawn Pruitt', party: 'Democratic' },
            { name: 'Carolyn Fitch', party: 'Republican' },
          ],
          referendum_question: null,
          referendum_yes_meaning: null,
          referendum_no_meaning: null,
        },
        {
          id: `${electionId}-railroad-commissioner`,
          election_id: electionId,
          office: 'Railroad Commissioner',
          contest_type: 'candidate',
          district: stateName,
          candidates: [
            { name: 'Alicia Dominguez', party: 'Democratic' },
            { name: 'Rex Calloway', party: 'Republican' },
            { name: 'Paul Mercer', party: 'Libertarian' },
          ],
          referendum_question: null,
          referendum_yes_meaning: null,
          referendum_no_meaning: null,
        },
        // === STATEWIDE JUDICIAL ===
        {
          id: `${electionId}-supreme-court-p2`,
          election_id: electionId,
          office: 'Justice, Supreme Court, Place 2',
          contest_type: 'candidate',
          district: stateName,
          candidates: [
            { name: 'Priya Anand', party: 'Democratic' },
            { name: 'Brett Aldridge', party: 'Republican' },
          ],
          referendum_question: null,
          referendum_yes_meaning: null,
          referendum_no_meaning: null,
        },
        {
          id: `${electionId}-supreme-court-p4`,
          election_id: electionId,
          office: 'Justice, Supreme Court, Place 4',
          contest_type: 'candidate',
          district: stateName,
          candidates: [
            { name: 'Otis Franklin', party: 'Democratic' },
            { name: 'Janet Lowell', party: 'Republican' },
          ],
          referendum_question: null,
          referendum_yes_meaning: null,
          referendum_no_meaning: null,
        },
        {
          id: `${electionId}-supreme-court-p6`,
          election_id: electionId,
          office: 'Justice, Supreme Court, Place 6',
          contest_type: 'candidate',
          district: stateName,
          candidates: [
            { name: 'Maria Estevez', party: 'Democratic' },
            { name: 'Gordon Pierce', party: 'Republican' },
          ],
          referendum_question: null,
          referendum_yes_meaning: null,
          referendum_no_meaning: null,
        },
        {
          id: `${electionId}-cca-presiding-judge`,
          election_id: electionId,
          office: 'Presiding Judge, Court of Criminal Appeals',
          contest_type: 'candidate',
          district: stateName,
          candidates: [
            { name: 'Leon Watkins', party: 'Democratic' },
            { name: 'Sharon Taft', party: 'Republican' },
          ],
          referendum_question: null,
          referendum_yes_meaning: null,
          referendum_no_meaning: null,
        },
        {
          id: `${electionId}-cca-judge-p3`,
          election_id: electionId,
          office: 'Judge, Court of Criminal Appeals, Place 3',
          contest_type: 'candidate',
          district: stateName,
          candidates: [
            { name: 'Tonya Blackwood', party: 'Democratic' },
            { name: 'Arthur Simms', party: 'Republican' },
          ],
          referendum_question: null,
          referendum_yes_meaning: null,
          referendum_no_meaning: null,
        },
        // === STATE BOARD OF EDUCATION ===
        {
          id: `${electionId}-sboe`,
          election_id: electionId,
          office: 'Member, State Board of Education',
          contest_type: 'candidate',
          district: `${countyName} SBOE District`,
          candidates: [
            { name: 'Denise Park', party: 'Democratic' },
            { name: 'Russell Holt', party: 'Republican' },
          ],
          referendum_question: null,
          referendum_yes_meaning: null,
          referendum_no_meaning: null,
        },
        // === STATE LEGISLATIVE ===
        {
          id: `${electionId}-state-senate`,
          election_id: electionId,
          office: 'State Senator',
          contest_type: 'candidate',
          district: `${countyName} Senate District`,
          candidates: [
            { name: 'Diane Nakamura', party: 'Democratic' },
            { name: 'Craig Sutton', party: 'Republican' },
          ],
          referendum_question: null,
          referendum_yes_meaning: null,
          referendum_no_meaning: null,
        },
        {
          id: `${electionId}-state-rep`,
          election_id: electionId,
          office: 'State Representative',
          contest_type: 'candidate',
          district: `${countyName} House District`,
          candidates: [
            { name: 'Kevin Morales', party: 'Democratic' },
            { name: 'Patricia Burns', party: 'Republican' },
          ],
          referendum_question: null,
          referendum_yes_meaning: null,
          referendum_no_meaning: null,
        },
        // === COUNTY OFFICES ===
        {
          id: `${electionId}-county-judge`,
          election_id: electionId,
          office: 'County Judge',
          contest_type: 'candidate',
          district: countyName,
          candidates: [
            { name: 'Sylvia Garza', party: 'Democratic' },
            { name: 'Howard Nash', party: 'Republican' },
          ],
          referendum_question: null,
          referendum_yes_meaning: null,
          referendum_no_meaning: null,
        },
        {
          id: `${electionId}-sheriff`,
          election_id: electionId,
          office: 'Sheriff',
          contest_type: 'candidate',
          district: countyName,
          candidates: [
            { name: 'Robert Vasquez', party: 'Democratic' },
            { name: 'Linda Chambers', party: 'Republican' },
          ],
          referendum_question: null,
          referendum_yes_meaning: null,
          referendum_no_meaning: null,
        },
        {
          id: `${electionId}-district-attorney`,
          election_id: electionId,
          office: 'District Attorney',
          contest_type: 'candidate',
          district: countyName,
          candidates: [
            { name: 'Marcus Webb', party: 'Democratic' },
            { name: 'Anne Thornton', party: 'Republican' },
          ],
          referendum_question: null,
          referendum_yes_meaning: null,
          referendum_no_meaning: null,
        },
        {
          id: `${electionId}-county-clerk`,
          election_id: electionId,
          office: 'County Clerk',
          contest_type: 'candidate',
          district: countyName,
          candidates: [
            { name: 'Grace Kim', party: 'Democratic' },
            { name: 'Bruce Stafford', party: 'Republican' },
          ],
          referendum_question: null,
          referendum_yes_meaning: null,
          referendum_no_meaning: null,
        },
        {
          id: `${electionId}-tax-assessor`,
          election_id: electionId,
          office: 'Tax Assessor-Collector',
          contest_type: 'candidate',
          district: countyName,
          candidates: [
            { name: 'Natalie Cross', party: 'Democratic' },
            { name: 'James Rutherford', party: 'Republican' },
          ],
          referendum_question: null,
          referendum_yes_meaning: null,
          referendum_no_meaning: null,
        },
        {
          id: `${electionId}-commissioner-p1`,
          election_id: electionId,
          office: 'County Commissioner, Precinct 1',
          contest_type: 'candidate',
          district: `${countyName} Precinct 1`,
          candidates: [
            { name: 'Tanya Osei', party: 'Democratic' },
            { name: 'Walter Griffith', party: 'Republican' },
          ],
          referendum_question: null,
          referendum_yes_meaning: null,
          referendum_no_meaning: null,
        },
        // === LOCAL JUDICIAL ===
        {
          id: `${electionId}-district-court-judge`,
          election_id: electionId,
          office: 'District Court Judge',
          contest_type: 'candidate',
          district: `${countyName} District Court`,
          candidates: [
            { name: 'Sandra Lee', party: 'Democratic' },
            { name: 'Paul Windsor', party: 'Republican' },
          ],
          referendum_question: null,
          referendum_yes_meaning: null,
          referendum_no_meaning: null,
        },
        {
          id: `${electionId}-jop-p1`,
          election_id: electionId,
          office: 'Justice of the Peace, Precinct 1',
          contest_type: 'candidate',
          district: `${countyName} Precinct 1`,
          candidates: [
            { name: 'Harold Dixon', party: 'Democratic' },
            { name: 'Connie Baker', party: 'Republican' },
          ],
          referendum_question: null,
          referendum_yes_meaning: null,
          referendum_no_meaning: null,
        },
        // === BALLOT MEASURES ===
        {
          id: `${electionId}-prop-1`,
          election_id: electionId,
          office: null,
          contest_type: 'referendum',
          district: `${stateName} Statewide`,
          candidates: null,
          referendum_question: `Proposition 1: ${stateName} Constitutional Amendment — Property Tax Relief`,
          referendum_yes_meaning: `Amends the ${stateName} Constitution to increase the homestead exemption for school district property taxes from $40,000 to $70,000, reducing the taxable value of a primary residence for most homeowners.`,
          referendum_no_meaning: `Homestead exemption remains at $40,000; no change to current property tax calculations for school district taxes.`,
        },
        {
          id: `${electionId}-prop-2`,
          election_id: electionId,
          office: null,
          contest_type: 'referendum',
          district: `${stateName} Statewide`,
          candidates: null,
          referendum_question: `Proposition 2: ${stateName} Constitutional Amendment — Water Infrastructure Fund`,
          referendum_yes_meaning: `Authorizes the legislature to create a water infrastructure fund to provide financing for water supply and conservation projects across the state.`,
          referendum_no_meaning: `No new constitutional fund created; water infrastructure projects continue to rely on existing state and local funding mechanisms.`,
        },
        {
          id: `${electionId}-measure-a`,
          election_id: electionId,
          office: null,
          contest_type: 'referendum',
          district: countyName,
          candidates: null,
          referendum_question: `Measure A: ${countyName} Infrastructure Bond`,
          referendum_yes_meaning: `Authorizes $250 million in general obligation bonds to fund road repairs, bridge maintenance, and public transit improvements throughout ${countyName}.`,
          referendum_no_meaning: `No new bonds issued; infrastructure projects rely on existing county budget allocations and annual appropriations.`,
        },
      ],
    },
  ]
}

export const MOCK_ELECTIONS: (Election & { contests: Contest[] })[] = [
  {
    id: 'mock-election-1',
    external_id: 'mock-general-2024',
    name: 'November General Election 2024',
    election_date: '2024-11-05',
    state: 'CA',
    zipcodes: null,
    contests: [
      {
        id: 'mock-contest-1',
        election_id: 'mock-election-1',
        office: 'President and Vice President',
        contest_type: 'candidate',
        district: 'United States',
        candidates: [
          { name: 'Kamala Harris / Tim Walz', party: 'Democratic', website: 'https://example.com' },
          { name: 'Donald Trump / JD Vance', party: 'Republican', website: 'https://example.com' },
          { name: 'Jill Stein / Butch Ware', party: 'Green', website: 'https://example.com' },
          { name: 'Chase Oliver / Mike ter Maat', party: 'Libertarian', website: 'https://example.com' },
        ],
        referendum_question: null,
        referendum_yes_meaning: null,
        referendum_no_meaning: null,
      },
      {
        id: 'mock-contest-2',
        election_id: 'mock-election-1',
        office: 'U.S. Senator',
        contest_type: 'candidate',
        district: 'California',
        candidates: [
          { name: 'Adam Schiff', party: 'Democratic', website: 'https://example.com' },
          { name: 'Steve Garvey', party: 'Republican', website: 'https://example.com' },
        ],
        referendum_question: null,
        referendum_yes_meaning: null,
        referendum_no_meaning: null,
      },
      {
        id: 'mock-contest-3',
        election_id: 'mock-election-1',
        office: 'U.S. Representative',
        contest_type: 'candidate',
        district: '12th Congressional District',
        candidates: [
          { name: 'Lateefah Simon', party: 'Democratic', website: 'https://example.com' },
          { name: 'Jennifer Tran', party: 'Democratic', website: 'https://example.com' },
        ],
        referendum_question: null,
        referendum_yes_meaning: null,
        referendum_no_meaning: null,
      },
      {
        id: 'mock-contest-4',
        election_id: 'mock-election-1',
        office: 'State Senator',
        contest_type: 'candidate',
        district: '9th State Senate District',
        candidates: [
          { name: 'Nancy Skinner', party: 'Democratic', website: 'https://example.com' },
          { name: 'Royce Brooks', party: 'Republican', website: 'https://example.com' },
        ],
        referendum_question: null,
        referendum_yes_meaning: null,
        referendum_no_meaning: null,
      },
      {
        id: 'mock-contest-5',
        election_id: 'mock-election-1',
        office: 'State Assembly Member',
        contest_type: 'candidate',
        district: '18th State Assembly District',
        candidates: [
          { name: 'Mia Bonta', party: 'Democratic', website: 'https://example.com' },
          { name: 'Dennis Linthicum', party: 'Republican', website: 'https://example.com' },
        ],
        referendum_question: null,
        referendum_yes_meaning: null,
        referendum_no_meaning: null,
      },
      {
        id: 'mock-contest-6',
        election_id: 'mock-election-1',
        office: null,
        contest_type: 'referendum',
        district: 'California Statewide',
        candidates: null,
        referendum_question: 'Proposition 2: School Facilities Bond',
        referendum_yes_meaning:
          'Authorizes $10 billion in bonds to fund construction, renovation, and modernization of K-12 schools and community colleges.',
        referendum_no_meaning:
          'No bond issued; school facility improvements rely on existing local and state funding.',
      },
      {
        id: 'mock-contest-7',
        election_id: 'mock-election-1',
        office: null,
        contest_type: 'referendum',
        district: 'California Statewide',
        candidates: null,
        referendum_question: 'Proposition 3: Constitutional Right to Marry',
        referendum_yes_meaning:
          'Removes the definition of marriage as between a man and a woman from the California Constitution and establishes a constitutional right to marry regardless of race, ethnicity, national origin, or sex.',
        referendum_no_meaning:
          'Retains existing constitutional language; no change to current marriage statutes.',
      },
      {
        id: 'mock-contest-8',
        election_id: 'mock-election-1',
        office: null,
        contest_type: 'referendum',
        district: 'California Statewide',
        candidates: null,
        referendum_question: 'Proposition 4: Climate and Clean Energy Bond',
        referendum_yes_meaning:
          'Authorizes $10 billion in bonds for water supply, wildfire prevention, clean air, parks, and coastal resilience projects.',
        referendum_no_meaning:
          'No bond issued; climate and clean energy projects funded through existing budgets only.',
      },
      {
        id: 'mock-contest-9',
        election_id: 'mock-election-1',
        office: null,
        contest_type: 'referendum',
        district: 'California Statewide',
        candidates: null,
        referendum_question: 'Proposition 5: Lower Vote Threshold for Local Housing and Infrastructure Bonds',
        referendum_yes_meaning:
          'Allows local governments to pass bonds for affordable housing and public infrastructure with 55% voter approval rather than the current two-thirds supermajority.',
        referendum_no_meaning:
          'Maintains the two-thirds supermajority requirement for local bonds funding housing and infrastructure.',
      },
      {
        id: 'mock-contest-10',
        election_id: 'mock-election-1',
        office: null,
        contest_type: 'referendum',
        district: 'California Statewide',
        candidates: null,
        referendum_question: 'Proposition 6: End Forced Prison Labor',
        referendum_yes_meaning:
          'Amends the California Constitution to prohibit the use of involuntary servitude as punishment for crime, ending compulsory unpaid or low-paid labor for incarcerated people.',
        referendum_no_meaning:
          'Retains the existing constitutional provision allowing involuntary servitude as criminal punishment.',
      },
      {
        id: 'mock-contest-11',
        election_id: 'mock-election-1',
        office: null,
        contest_type: 'referendum',
        district: 'California Statewide',
        candidates: null,
        referendum_question: 'Proposition 32: Raise the Minimum Wage',
        referendum_yes_meaning:
          'Increases the state minimum wage to $18 per hour for most workers by January 2025.',
        referendum_no_meaning:
          'Minimum wage remains on its current schedule at $16/hour with no additional increase.',
      },
      {
        id: 'mock-contest-12',
        election_id: 'mock-election-1',
        office: null,
        contest_type: 'referendum',
        district: 'California Statewide',
        candidates: null,
        referendum_question: 'Proposition 33: Expands Local Rent Control',
        referendum_yes_meaning:
          'Repeals state restrictions on local rent control ordinances, allowing cities and counties to expand rent control to more units including single-family homes and newer buildings.',
        referendum_no_meaning:
          'Maintains current state limits on local rent control; the Costa-Hawkins Rental Housing Act remains in effect.',
      },
      {
        id: 'mock-contest-13',
        election_id: 'mock-election-1',
        office: null,
        contest_type: 'referendum',
        district: 'California Statewide',
        candidates: null,
        referendum_question: 'Proposition 35: Make Medi-Cal Funding Permanent',
        referendum_yes_meaning:
          'Makes permanent the existing managed care organization tax that funds Medi-Cal healthcare services, locking in billions in federal matching funds annually.',
        referendum_no_meaning:
          'Allows the temporary managed care tax to expire; Medi-Cal funding would depend on future legislative action.',
      },
      {
        id: 'mock-contest-14',
        election_id: 'mock-election-1',
        office: null,
        contest_type: 'referendum',
        district: 'California Statewide',
        candidates: null,
        referendum_question: 'Proposition 36: Increase Penalties for Drug and Theft Crimes',
        referendum_yes_meaning:
          'Increases penalties for certain drug and theft crimes, allows felony charges for repeat shoplifting, and creates a new treatment-mandated felony for fentanyl and meth possession.',
        referendum_no_meaning:
          'Maintains current sentencing under Proposition 47; no new felony categories for repeat theft or drug possession.',
      },
      {
        id: 'mock-contest-15',
        election_id: 'mock-election-1',
        office: null,
        contest_type: 'referendum',
        district: 'Alameda County',
        candidates: null,
        referendum_question: 'Measure B: Alameda County Transportation Commission Sales Tax',
        referendum_yes_meaning:
          'Renews a half-cent sales tax for 30 years to fund local street repairs, public transit, bicycle and pedestrian improvements, and paratransit services in Alameda County.',
        referendum_no_meaning:
          'Sales tax expires; transportation projects funded through this measure would lose their dedicated funding source.',
      },
    ],
  },
  {
    id: 'mock-election-2',
    external_id: 'mock-primary-2024',
    name: 'State Primary Election 2024',
    election_date: '2024-03-05',
    state: 'CA',
    zipcodes: null,
    contests: [
      {
        id: 'mock-contest-16',
        election_id: 'mock-election-2',
        office: 'President of the United States (Primary)',
        contest_type: 'candidate',
        district: 'United States',
        candidates: [
          { name: 'Joe Biden', party: 'Democratic', website: 'https://example.com' },
          { name: 'Donald Trump', party: 'Republican', website: 'https://example.com' },
          { name: 'Nikki Haley', party: 'Republican', website: 'https://example.com' },
          { name: 'Dean Phillips', party: 'Democratic', website: 'https://example.com' },
        ],
        referendum_question: null,
        referendum_yes_meaning: null,
        referendum_no_meaning: null,
      },
      {
        id: 'mock-contest-17',
        election_id: 'mock-election-2',
        office: 'U.S. Senator (Primary)',
        contest_type: 'candidate',
        district: 'California',
        candidates: [
          { name: 'Adam Schiff', party: 'Democratic', website: 'https://example.com' },
          { name: 'Steve Garvey', party: 'Republican', website: 'https://example.com' },
          { name: 'Katie Porter', party: 'Democratic', website: 'https://example.com' },
          { name: 'Barbara Lee', party: 'Democratic', website: 'https://example.com' },
        ],
        referendum_question: null,
        referendum_yes_meaning: null,
        referendum_no_meaning: null,
      },
      {
        id: 'mock-contest-18',
        election_id: 'mock-election-2',
        office: 'Governor',
        contest_type: 'candidate',
        district: 'California',
        candidates: [
          { name: 'Gavin Newsom', party: 'Democratic', website: 'https://example.com' },
          { name: 'Brian Dahle', party: 'Republican', website: 'https://example.com' },
        ],
        referendum_question: null,
        referendum_yes_meaning: null,
        referendum_no_meaning: null,
      },
      {
        id: 'mock-contest-19',
        election_id: 'mock-election-2',
        office: 'Attorney General',
        contest_type: 'candidate',
        district: 'California',
        candidates: [
          { name: 'Rob Bonta', party: 'Democratic', website: 'https://example.com' },
          { name: 'Nathan Hochman', party: 'Republican', website: 'https://example.com' },
        ],
        referendum_question: null,
        referendum_yes_meaning: null,
        referendum_no_meaning: null,
      },
      {
        id: 'mock-contest-20',
        election_id: 'mock-election-2',
        office: null,
        contest_type: 'referendum',
        district: 'California Statewide',
        candidates: null,
        referendum_question: 'Proposition 1: Mental Health Services Overhaul',
        referendum_yes_meaning:
          'Restructures mental health funding to prioritize housing and treatment for those with severe mental illness and authorizes $6.38 billion in bonds for new treatment facilities.',
        referendum_no_meaning:
          'Current Mental Health Services Act distribution formula is maintained; no new bond for treatment facilities.',
      },
      {
        id: 'mock-contest-21',
        election_id: 'mock-election-2',
        office: 'Alameda County District Attorney',
        contest_type: 'candidate',
        district: 'Alameda County',
        candidates: [
          { name: 'Pamela Price', party: 'Democratic', website: 'https://example.com' },
          { name: 'Michael Hutchinson', party: 'Democratic', website: 'https://example.com' },
        ],
        referendum_question: null,
        referendum_yes_meaning: null,
        referendum_no_meaning: null,
      },
    ],
  },
  {
    id: 'mock-election-3',
    external_id: 'mock-special-2024',
    name: 'Special Municipal Election 2024',
    election_date: '2024-06-04',
    state: 'CA',
    zipcodes: null,
    contests: [
      {
        id: 'mock-contest-22',
        election_id: 'mock-election-3',
        office: 'Mayor',
        contest_type: 'candidate',
        district: 'City of Oakland',
        candidates: [
          { name: 'Sheng Thao', party: 'Nonpartisan', website: 'https://example.com' },
          { name: 'Loren Taylor', party: 'Nonpartisan', website: 'https://example.com' },
          { name: 'Tyron Jordan', party: 'Nonpartisan', website: 'https://example.com' },
        ],
        referendum_question: null,
        referendum_yes_meaning: null,
        referendum_no_meaning: null,
      },
      {
        id: 'mock-contest-23',
        election_id: 'mock-election-3',
        office: 'City Council Member',
        contest_type: 'candidate',
        district: 'Oakland District 2',
        candidates: [
          { name: 'Nikki Fortunato Bas', party: 'Nonpartisan', website: 'https://example.com' },
          { name: 'Jorge Lerma', party: 'Nonpartisan', website: 'https://example.com' },
        ],
        referendum_question: null,
        referendum_yes_meaning: null,
        referendum_no_meaning: null,
      },
      {
        id: 'mock-contest-24',
        election_id: 'mock-election-3',
        office: null,
        contest_type: 'referendum',
        district: 'City of Oakland',
        candidates: null,
        referendum_question: 'Measure T: Vacant Property Tax',
        referendum_yes_meaning:
          'Imposes an annual tax on vacant commercial and residential properties to incentivize development and reduce blight.',
        referendum_no_meaning:
          'No new tax on vacant properties; existing property tax rates remain unchanged.',
      },
      {
        id: 'mock-contest-25',
        election_id: 'mock-election-3',
        office: null,
        contest_type: 'referendum',
        district: 'Oakland Unified School District',
        candidates: null,
        referendum_question: 'Measure Y: Oakland Schools Parcel Tax',
        referendum_yes_meaning:
          'Renews a parcel tax of $120 per year per parcel for 8 years to fund Oakland public school programs including arts, music, and class size reduction.',
        referendum_no_meaning:
          'Parcel tax expires; programs currently funded by the tax would need alternative funding sources.',
      },
    ],
  },
]
